// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'XXX',
    appId: 'XXX',
    messagingSenderId: 'XXX',
    projectId: 'leafchat-XXX',
    authDomain: 'leafchat-XXXX.firebaseapp.com',
    storageBucket: 'leafchat-XXXX.firebasestorage.app',
    measurementId: 'G-XXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'XXX-XXX',
    appId: 'XXX-XXX',
    messagingSenderId: 'XXX',
    projectId: 'leafchat-bb3a2',
    storageBucket: 'leafchat-XXXX.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'XXXX',
    appId: 'XXXX',
    messagingSenderId: 'XXXX',
    projectId: 'leafchat-XXXX',
    storageBucket: 'leafchat-XXXX.firebasestorage.app',
    iosBundleId: 'com.example.appMsg',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'XXXXX',
    appId: 'XXXXX',
    messagingSenderId: 'XXXX',
    projectId: 'leafchat-XXXX',
    storageBucket: 'leafchat-XXXX.firebasestorage.app',
    iosBundleId: 'com.example.appMsg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'XXXX',
    appId: 'XXXX',
    messagingSenderId: 'XXXX',
    projectId: 'leafchat-XXX',
    authDomain: 'leafchat-XXXXX.firebaseapp.com',
    storageBucket: 'leafchat-XXXXX.firebasestorage.app',
    measurementId: 'G-XXX',
  );
}
