// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc7NRYfgU4V-CSJm632jwkynJe6AP5DCY',
    appId: '1:810235961716:web:1a9cfdda4dbbc5bf780c21',
    messagingSenderId: '810235961716',
    projectId: 'leafchat-bb3a2',
    authDomain: 'leafchat-bb3a2.firebaseapp.com',
    storageBucket: 'leafchat-bb3a2.firebasestorage.app',
    measurementId: 'G-BNRF9P6YPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdOjeYfSVv1wNY7LteETYVP47KMsWdS4U',
    appId: '1:810235961716:android:7ee5eef3b3902cac780c21',
    messagingSenderId: '810235961716',
    projectId: 'leafchat-bb3a2',
    storageBucket: 'leafchat-bb3a2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCipGyKk--Ht0EwicrEtmt0gF_-zDCOtUs',
    appId: '1:810235961716:ios:c2e4ed247f0b17d2780c21',
    messagingSenderId: '810235961716',
    projectId: 'leafchat-bb3a2',
    storageBucket: 'leafchat-bb3a2.firebasestorage.app',
    iosBundleId: 'com.example.appMsg',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCipGyKk--Ht0EwicrEtmt0gF_-zDCOtUs',
    appId: '1:810235961716:ios:c2e4ed247f0b17d2780c21',
    messagingSenderId: '810235961716',
    projectId: 'leafchat-bb3a2',
    storageBucket: 'leafchat-bb3a2.firebasestorage.app',
    iosBundleId: 'com.example.appMsg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc7NRYfgU4V-CSJm632jwkynJe6AP5DCY',
    appId: '1:810235961716:web:1a9cfdda4dbbc5bf780c21',
    messagingSenderId: '810235961716',
    projectId: 'leafchat-bb3a2',
    authDomain: 'leafchat-bb3a2.firebaseapp.com',
    storageBucket: 'leafchat-bb3a2.firebasestorage.app',
    measurementId: 'G-BNRF9P6YPV',
  );
}
